[package]
name = "grep-like-cli"
version = "0.1.0"
authors = ["Viktor Doroshenko <vdoroshenko@vente-privee.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
